### ISSUE TITLE
Add option to translate messages

### ISSUE THREAD

**Issue by crashzk** [Summer-16/CSGO-NonPrimePlayerKicker#3] opened 2020-03-20 14:22 UTC
Add option to translate messages.

That is, I could create a file of translations for the plugin, I would like to translate the kick messages into my language, kind of just having to compile the plugin to do this.

I would be grateful if you had the option of translations.

And congratulations on the plugin, so far everything perfect for me, I didn't notice any bugs.

**Comment by Summer-16** [comment] 2020-03-23 13:30
actually it's a nice idea, I will do my best to make a release with translation as soon as possible.

**Comment by crashzk** [comment] 2020-03-23 15:39
> actually it's a nice idea, I will do my best to make a release with translation as soon as possible.

Perfect, I believe it doesn't even have to be a translation file.

You could make the plugin create a configuration file, and put a CVAR that controls the message that is displayed to the player when it is expelled.

Same thing for option to put TAG that you recently added, leave a CVAR so that we can change the TAG if you want. https://github.com/Summer-16/CSGO-NonPrimePlayerKicker/issues/2

**Comment by Summer-16** [comment] 2020-03-24 05:45
[NonPrimeKicker.zip](https://github.com/Summer-16/CSGO-NonPrimePlayerKicker/files/4373388/NonPrimeKicker.zip)

Hi,
I have compiled a version with config, can you do a quick test and provide some feedback

**Comment by crashzk** [comment] 2020-03-24 20:42
> [NonPrimeKicker.zip](https://github.com/Summer-16/CSGO-NonPrimePlayerKicker/files/4373388/NonPrimeKicker.zip)
> 
> Hi,
> I have compiled a version with config, can you do a quick test and provide some feedback

So far with no errors in the plugin, it generated the configs, all right.

I will test now if he is really kicking the players that do not have the Prime CSGO Status or if he does not have the Level configured.

Soon I will provide more information, thanks for now!

**Comment by crashzk** [comment] 2020-03-25 18:09
@Summer-16 

I believe there is a BUG, ​​there is a player that has the Prime Status, but he cannot connect to the server, he says he needs to be Prime.

Here is a print showing that he has all the requirements, but still takes the kick.
https://prnt.sc/rmoyt3
https://prnt.sc/rmoykj

As you can see he has Prime, but he said he got Prime by leveling it up, when he reached 21 in the case, I don't know if it changes something.

I changed the minimum level to enter too, I left 1 and still nothing, he can't.

I don't know if it would be a NonPrime Player Kicker BUG, ​​or if it would be a SteamWorks extension.

**[EDIT1]**
I already have a suggestion, if I set the CVAR `sm_npmk_kicklevel` to zero, `sm_npmk_kicklevel "0"` this check would be disabled, I would just check if the player has the Prime Status or not. It would be possible?

**Comment by Summer-16** [comment] 2020-03-25 19:05
Actually thats not a bug the plugin is working as expected.

About getting prime there are 2 cases
- 1st you buy it and steam will give you access to license of game that is what we are checking in the plugin 
- 2nd you grind it by getting to level 21 and they give you prime access but still not the license they are just allowing you to play in prime 

Now as we check for license in our plugin peoples who got prime by going to level 21 will still be counted as non prime, so thats why to filter some categories of non prime i implemented that level check. 

But in case of your player as i can see in SS he is back to level 1 after getting medal so he needs to get to the threshold level again.

*also if anyone bought the prime later he needs to reinstall the game to update game files

**Comment by crashzk** [comment] 2020-03-25 22:01
I understood, in this case, there would be no way to implement a database in the plugin?

That is, the players that were checked / authorized to enter the server, only their data would be saved in this database, even if his level is reset after he gets the medal, he could normally enter the server.

Would it be possible, or would it be out of your current project for the plugin?

**Comment by Summer-16** [comment] 2020-03-26 09:01
Well, we can try the database approach not a bad idea.
I am adding that in my todo for now
Closing this issue as message config is done.

**Closed as completed by Summer-16** 2020-03-26 09:01 UTC
Labels: enhancement
